export interface ServiceField {
  name: string
  label: string
  type: 'text' | 'email' | 'tel' | 'number' | 'date' | 'select' | 'checkbox' | 'textarea' | 'radio'
  placeholder?: string
  required?: boolean
  options?: { label: string; value: string }[]
  validation?: string
  helpText?: string
}

export interface Service {
  id: string
  slug: string
  title: string
  shortDescription: string
  fullDescription: string
  icon: string
  heroImage: string
  problemStatement: string
  solutionPoints: string[]
  processSteps: { step: number; title: string; description: string }[]
  successMetrics: { metric: string; value: string }[]
  formFields: ServiceField[]
  faqItems: { question: string; answer: string }[]
  crmFormUrl: string
}

export const services: Service[] = [
  {
    id: '1',
    slug: 'credit-cibil-analysis',
    title: 'Credit & CIBIL Analysis',
    shortDescription: 'Detailed analysis of your credit bureau reports to identify errors and improve your credit health.',
    fullDescription: 'Our experts conduct a thorough analysis of your credit bureau reports to identify and explain errors, risk factors, and inconsistencies. We provide structured correction guidance to improve your creditworthiness.',
    icon: 'FileText',
    heroImage: '/images/credit-report.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/631de182d7eeb38378b0b805420d7816',
    problemStatement: 'A low CIBIL score can cost you thousands in higher interest rates or loan rejections. Errors on your report—some not even your fault—can damage your financial future for years.',
    solutionPoints: [
      'Expert analysis of all 4 credit bureaus',
      'Identification of data errors and discrepancies',
      'Dispute filing & follow-up support',
      'Personalized credit improvement roadmap',
    ],
    processSteps: [
      { step: 1, title: 'Report Retrieval', description: 'We obtain your credit reports from all bureaus.' },
      { step: 2, title: 'Analysis & Review', description: 'Expert analysis to identify errors and areas for improvement.' },
      { step: 3, title: 'Dispute Filing', description: 'We initiate disputes for inaccurate entries with bureaus.' },
      { step: 4, title: 'Follow-up & Resolution', description: 'Continuous follow-up until errors are corrected.' },
    ],
    successMetrics: [
      { metric: 'Average CIBIL Improvement', value: '80-120 points' },
      { metric: 'Error Correction Rate', value: '85%+' },
      { metric: 'Average Resolution Time', value: '30-45 days' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'pan', label: 'PAN (optional)', type: 'text' },
      { name: 'cibilScore', label: 'Current CIBIL Score (if known)', type: 'number' },
      { name: 'lastCheckDate', label: 'When did you last check your CIBIL?', type: 'date' },
      { name: 'knownIssues', label: 'Known issues on your report', type: 'checkbox', options: [
        { label: 'Hard inquiries', value: 'hard-inquiries' },
        { label: 'Days past due (DPD)', value: 'dpd' },
        { label: 'High credit utilization', value: 'high-utilization' },
        { label: 'Multiple recent applications', value: 'multiple-applications' },
        { label: 'Not sure', value: 'not-sure' },
      ] },
      { name: 'problemDescription', label: 'Describe your main concern', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'How long does CIBIL analysis take?', answer: 'Initial analysis takes 2-3 business days. Full resolution can take 30-45 days depending on the number of disputes.' },
      { question: 'Can you guarantee a score improvement?', answer: 'We cannot guarantee a specific score, but we identify and dispute all inaccurate entries systematically.' },
      { question: 'Is there any upfront cost?', answer: 'No upfront costs. We discuss our fee structure after initial consultation.' },
    ],
  },
  {
    id: '2',
    slug: 'credit-report-rectification',
    title: 'Credit Report Rectification',
    shortDescription: 'Expert assistance in raising and tracking disputes for incorrect loan entries and outdated records.',
    fullDescription: 'We help you dispute and correct wrong entries on your credit report across all bureaus. Our team handles the entire dispute process and follows up until resolution.',
    icon: 'Edit',
    heroImage: '/images/credit-report.jpg',
    problemStatement: 'Even one wrong entry can pull down your credit score by 50+ points. Manual dispute filing is tedious and often ignored by bureaus.',
    solutionPoints: [
      'Expert dispute letter drafting',
      'Multi-bureau filing & tracking',
      'Automated follow-up & escalation',
      'Documentation & evidence gathering',
    ],
    processSteps: [
      { step: 1, title: 'Error Identification', description: 'Pinpoint exact incorrect entries needing correction.' },
      { step: 2, title: 'Documentation', description: 'Gather supporting documents and evidence.' },
      { step: 3, title: 'Dispute Filing', description: 'File formal disputes with respective bureaus.' },
      { step: 4, title: 'Resolution Tracking', description: 'Monitor and escalate until errors are rectified.' },
    ],
    successMetrics: [
      { metric: 'Dispute Success Rate', value: '88%' },
      { metric: 'Average Resolution Time', value: '45-60 days' },
      { metric: 'Customer Satisfaction', value: '94%' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'cibilScore', label: 'Current CIBIL Score (if known)', type: 'number' },
      { name: 'affectedBureaus', label: 'Which bureaus have the error?', type: 'checkbox', required: true, options: [
        { label: 'CIBIL', value: 'cibil' },
        { label: 'Equifax', value: 'equifax' },
        { label: 'Experian', value: 'experian' },
        { label: 'CRIF HighMark', value: 'crif' },
      ] },
      { name: 'disputeType', label: 'Type of dispute', type: 'checkbox', required: true, options: [
        { label: 'Wrong entry / not mine', value: 'wrong-entry' },
        { label: 'Incorrect balance', value: 'incorrect-balance' },
        { label: 'Paid account shown as unpaid', value: 'paid-as-unpaid' },
        { label: 'Duplicate account', value: 'duplicate' },
        { label: 'Account closed but showing as active', value: 'closed-active' },
      ] },
      { name: 'incorrectDetails', label: 'Details of incorrect information', type: 'textarea', required: true },
      { name: 'problemDescription', label: 'How is this affecting you?', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'How do I prove the error is not mine?', answer: 'We guide you through document collection and strengthen your dispute case with evidence.' },
      { question: 'Will this hurt my credit score further?', answer: 'Disputing errors will not harm your score. It helps improve it once resolved.' },
      { question: 'What if the bureau denies my dispute?', answer: 'We escalate to RBI and prepare for ombudsman complaints if needed.' },
    ],
  },
  {
    id: '3',
    slug: 'loan-emi-stress-guidance',
    title: 'Loan & EMI Stress Guidance',
    shortDescription: 'Support for individuals facing loan or EMI stress, including restructuring advice and creditor negotiation.',
    fullDescription: 'Struggling with EMI payments? We provide strategic guidance on loan restructuring, creditor negotiation, and financial planning to ease your burden.',
    icon: 'TrendingDown',
    heroImage: '/images/financial-growth.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/795c965aa825c7561c1fc188661b0e3f',
    problemStatement: 'Rising EMIs, job loss, or medical emergencies can make loan repayment impossible. Banks often reject restructuring requests, leaving you facing legal action.',
    solutionPoints: [
      'Loan restructuring negotiation',
      'EMI payment relief strategies',
      'Creditor communication & mediation',
      'Debt consolidation planning',
    ],
    processSteps: [
      { step: 1, title: 'Financial Assessment', description: 'Review your loans and financial situation.' },
      { step: 2, title: 'Restructuring Planning', description: 'Develop a sustainable repayment plan.' },
      { step: 3, title: 'Bank Negotiation', description: 'Negotiate with lenders for restructuring.' },
      { step: 4, title: 'Implementation & Support', description: 'Guide you through the restructuring process.' },
    ],
    successMetrics: [
      { metric: 'EMI Reduction Achieved', value: 'Average 20-30%' },
      { metric: 'Restructuring Success', value: '82%' },
      { metric: 'Client Retention', value: '91%' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'loanType', label: 'Type of loan', type: 'select', required: true, options: [
        { label: 'Home Loan', value: 'home-loan' },
        { label: 'Personal Loan', value: 'personal-loan' },
        { label: 'Auto Loan', value: 'auto-loan' },
        { label: 'Education Loan', value: 'education-loan' },
        { label: 'Multiple Loans', value: 'multiple-loans' },
      ] },
      { name: 'loanAmount', label: 'Loan amount (₹)', type: 'number', required: true },
      { name: 'emiAmount', label: 'Current EMI (₹)', type: 'number', required: true },
      { name: 'loanStatus', label: 'Current loan status', type: 'radio', required: true, options: [
        { label: 'Active', value: 'active' },
        { label: 'Overdue', value: 'overdue' },
        { label: 'Defaulted', value: 'defaulted' },
      ] },
      { name: 'stressReasons', label: 'Why are you facing EMI stress?', type: 'checkbox', required: true, options: [
        { label: 'Job loss / income reduction', value: 'income-reduction' },
        { label: 'Medical emergency', value: 'medical' },
        { label: 'Business slowdown', value: 'business-slowdown' },
        { label: 'Unexpected expenses', value: 'unexpected-expenses' },
        { label: 'Multiple loan obligations', value: 'multiple-loans' },
      ] },
      { name: 'problemDescription', label: 'Describe your situation in detail', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'Will restructuring affect my credit score?', answer: 'Restructuring may temporarily impact your score, but it prevents defaults which are far more damaging.' },
      { question: 'Can banks refuse restructuring?', answer: 'They can, but banks are often willing if you approach them with a solid financial plan.' },
      { question: 'How much can my EMI be reduced?', answer: 'Reductions vary (15-35%) based on your situation and bank policies.' },
    ],
  },
  {
    id: '4',
    slug: 'banking-credit-card-support',
    title: 'Banking & Credit Card Support',
    shortDescription: 'Assistance with unauthorized transactions, incorrect charges, billing disputes, and service-level grievances.',
    fullDescription: 'We handle disputes with banks and credit card companies, ensuring you get refunds for unauthorized charges and resolve billing errors quickly.',
    icon: 'CreditCard',
    heroImage: '/images/banking-support.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/6c228192a568a8a2a2ea8b655df6bed8',
    problemStatement: 'Fraudulent charges, billing errors, and poor customer service from banks can leave you stranded. Complaint resolution can take months without proper escalation.',
    solutionPoints: [
      'Fraud & unauthorized transaction investigation',
      'Billing dispute resolution',
      'Service complaint escalation',
      'Refund recovery & follow-up',
    ],
    processSteps: [
      { step: 1, title: 'Issue Documentation', description: 'Gather evidence of the unauthorized transaction or error.' },
      { step: 2, title: 'Formal Complaint Filing', description: 'File a complaint with the bank and ombudsman if needed.' },
      { step: 3, title: 'Investigation Tracking', description: 'Monitor bank investigation and keep them accountable.' },
      { step: 4, title: 'Refund & Resolution', description: 'Ensure refund is processed and issue is closed.' },
    ],
    successMetrics: [
      { metric: 'Complaint Resolution Rate', value: '89%' },
      { metric: 'Average Recovery Time', value: '15-30 days' },
      { metric: 'Amount Recovered', value: '₹1M+' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'institutionName', label: 'Bank / NBFC name', type: 'text', required: true },
      { name: 'issueType', label: 'Issue type', type: 'checkbox', required: true, options: [
        { label: 'Unauthorized transaction', value: 'unauthorized' },
        { label: 'Incorrect charges', value: 'incorrect-charges' },
        { label: 'Billing dispute', value: 'billing-dispute' },
        { label: 'Service failure', value: 'service-failure' },
      ] },
      { name: 'transactionDate', label: 'Date of transaction', type: 'date' },
      { name: 'amountInvolved', label: 'Amount involved (₹)', type: 'number' },
      { name: 'disputeNature', label: 'Detailed description of the issue', type: 'textarea', required: true },
      { name: 'problemDescription', label: 'Steps already taken', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'How quickly can I get a refund?', answer: 'Banks typically issue refunds within 15-30 days of investigation completion.' },
      { question: 'Do I need to provide all transaction details?', answer: 'Yes, provide transaction date, amount, merchant details, and any proof of dispute.' },
      { question: 'What if the bank denies my claim?', answer: 'We escalate to the Banking Ombudsman for dispute resolution.' },
    ],
  },
  {
    id: '5',
    slug: 'insurance-issue-assistance',
    title: 'Insurance Issue Assistance',
    shortDescription: 'Guidance for insurance problems including mis-selling complaints, policy corrections, and claim-related issues.',
    fullDescription: 'Navigate insurance disputes with expert support. From policy corrections to claim denials, we help resolve your insurance issues systematically.',
    icon: 'Shield',
    heroImage: '/images/financial-growth.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/33801dae0674a03b17cd19e4ec52d195',
    problemStatement: 'Insurance claims are frequently denied due to policy misunderstandings or deliberate mis-selling. Fighting the insurance company alone is daunting and expensive.',
    solutionPoints: [
      'Policy review & mis-selling identification',
      'Claim denial appeal assistance',
      'Policy amendment & correction support',
      'Ombudsman complaint escalation',
    ],
    processSteps: [
      { step: 1, title: 'Policy Review', description: 'Analyze your policy terms and coverage details.' },
      { step: 2, title: 'Issue Identification', description: 'Identify mis-selling or claim denial reasons.' },
      { step: 3, title: 'Appeal Filing', description: 'Prepare and file formal appeals with the insurer.' },
      { step: 4, title: 'Escalation & Resolution', description: 'Escalate to ombudsman if needed for resolution.' },
    ],
    successMetrics: [
      { metric: 'Claim Appeal Success', value: '76%' },
      { metric: 'Average Settlement Value', value: '₹3-5 Lakhs' },
      { metric: 'Resolution Time', value: '45-90 days' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'insuranceType', label: 'Type of insurance', type: 'select', required: true, options: [
        { label: 'Health Insurance', value: 'health' },
        { label: 'Life Insurance', value: 'life' },
        { label: 'Auto Insurance', value: 'auto' },
        { label: 'Property Insurance', value: 'property' },
        { label: 'Travel Insurance', value: 'travel' },
      ] },
      { name: 'policyNumber', label: 'Policy number', type: 'text', required: true },
      { name: 'issueType', label: 'Nature of issue', type: 'checkbox', required: true, options: [
        { label: 'Mis-selling complaint', value: 'mis-selling' },
        { label: 'Claim denial', value: 'claim-denial' },
        { label: 'Policy correction', value: 'policy-correction' },
        { label: 'Premium dispute', value: 'premium-dispute' },
      ] },
      { name: 'policyAge', label: 'How old is this policy?', type: 'text' },
      { name: 'claimStatus', label: 'Claim status (if applicable)', type: 'text' },
      { name: 'problemDescription', label: 'Describe the issue in detail', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'Can I contest a claim denial?', answer: 'Yes. We help appeal the decision with supporting documentation.' },
      { question: 'Is my policy too old to contest?', answer: 'There are no time limits for filing ombudsman complaints regarding mis-selling.' },
      { question: 'What documentation do I need?', answer: 'Policy documents, claim denial letter, medical reports (if applicable), and correspondence with the insurer.' },
    ],
  },
  {
    id: '6',
    slug: 'unclaimed-money-support',
    title: 'Unclaimed Money Support',
    shortDescription: 'Assistance in identifying and claiming unclaimed money from banks, mutual funds, and other financial institutions.',
    fullDescription: 'Recover your forgotten money. We help you search for and claim unclaimed deposits, dividends, and benefits from various financial institutions.',
    icon: 'Wallet',
    heroImage: '/images/financial-growth.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/3aa01212d392d4b44c48651acfb970d2',
    problemStatement: 'Millions of rupees lie unclaimed in bank accounts, dormant deposits, and dividend accounts. Most people don\'t know how to find or claim their money.',
    solutionPoints: [
      'Comprehensive unclaimed money search',
      'Multi-institution database access',
      'Claim filing & documentation',
      'Follow-up & fund recovery',
    ],
    processSteps: [
      { step: 1, title: 'Search Initiation', description: 'Search across banks, mutual funds, IEPF, and other databases.' },
      { step: 2, title: 'Identification', description: 'Identify all unclaimed money linked to your name/account.' },
      { step: 3, title: 'Claim Preparation', description: 'Prepare and file claims with supporting documents.' },
      { step: 4, title: 'Fund Recovery', description: 'Monitor claims and ensure funds are transferred to you.' },
    ],
    successMetrics: [
      { metric: 'Money Found Per Person', value: 'Average ₹50K-2L' },
      { metric: 'Claim Success Rate', value: '95%+' },
      { metric: 'Average Processing Time', value: '30-60 days' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'pan', label: 'PAN (optional)', type: 'text' },
      { name: 'searchKeywords', label: 'Names or identifiers to search', type: 'text', required: true, placeholder: 'Your name, parent name, company name, etc.' },
      { name: 'institutions', label: 'Which institutions to search?', type: 'checkbox', required: true, options: [
        { label: 'Banks (IEPF)', value: 'banks' },
        { label: 'Mutual Funds', value: 'mutual-funds' },
        { label: 'Insurance Companies', value: 'insurance' },
        { label: 'Pension Funds', value: 'pension' },
        { label: 'Stock Market (CDSL/NSDL)', value: 'stock-market' },
        { label: 'All', value: 'all' },
      ] },
      { name: 'periodSearched', label: 'Time period of concern (e.g., 2010-2015)', type: 'text' },
      { name: 'problemDescription', label: 'Any specific accounts or investments you remember?', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'How do you find unclaimed money?', answer: 'We search through IEPF, bank databases, mutual fund records, and insurance company records.' },
      { question: 'Is there a fee to search?', answer: 'We discuss fees after search completion and only once money is found.' },
      { question: 'Can money be really unclaimed after decades?', answer: 'Yes! Thousands of rupees remain unclaimed indefinitely. We can help recover it.' },
    ],
  },
  {
    id: '7',
    slug: 'grievance-complaint-escalation',
    title: 'Grievance & Complaint Escalation',
    shortDescription: 'Support in drafting, filing, and escalating complaints with banks, NBFCs, insurers, regulators, and ombudsman.',
    fullDescription: 'Your complaints deserve to be heard. We ensure proper escalation through regulatory channels, ombudsman, and public authorities for maximum impact.',
    icon: 'AlertCircle',
    heroImage: '/images/banking-support.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/f3e61b812c78dd98268ebd6340a5a3d7',
    problemStatement: 'Filing complaints to the right authority is complex. Most complaints go unresolved because they\'re filed incorrectly or not escalated properly.',
    solutionPoints: [
      'Regulatory complaint strategy',
      'Ombudsman complaint filing',
      'Escalation to RBI / SEBI / IRDA',
      'Public authority complaints',
    ],
    processSteps: [
      { step: 1, title: 'Complaint Assessment', description: 'Review your issue and identify correct authority.' },
      { step: 2, title: 'Documentation', description: 'Gather and organize evidence for strong complaints.' },
      { step: 3, title: 'Multi-level Filing', description: 'File with institution → ombudsman → regulator.' },
      { step: 4, title: 'Follow-up & Resolution', description: 'Actively track and push for resolution.' },
    ],
    successMetrics: [
      { metric: 'Complaint Resolution Rate', value: '81%' },
      { metric: 'Average Follow-up Time', value: '60-90 days' },
      { metric: 'Escalation Success', value: '74%' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'previousComplaintFiled', label: 'Have you already filed a complaint?', type: 'radio', required: true, options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ] },
      { name: 'complaintRefNumber', label: 'Complaint reference number (if filed)', type: 'text' },
      { name: 'institutionName', label: 'Institution name', type: 'text', required: true },
      { name: 'complaintDetails', label: 'Detailed complaint narrative', type: 'textarea', required: true, placeholder: 'Explain what happened, when, and how it affected you' },
      { name: 'expectedTimeline', label: 'When did this issue occur?', type: 'date' },
      { name: 'problemDescription', label: 'What resolution are you seeking?', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'What\'s the difference between ombudsman and RBI complaint?', answer: 'Ombudsman handles individual consumer disputes; RBI addresses systemic banking issues.' },
      { question: 'How long does ombudsman take?', answer: 'Ombudsman decisions typically come within 60-90 days.' },
      { question: 'Can I file multiple complaints?', answer: 'Yes, with different authorities for stronger leverage and wider coverage.' },
    ],
  },
  {
    id: '8',
    slug: 'documentation-case-facilitation',
    title: 'Documentation & Case Facilitation',
    shortDescription: 'End-to-end assistance in preparing documents, representations, and case files for financial issue resolution.',
    fullDescription: 'From affidavits to detailed representations, we prepare comprehensive documentation to strengthen your case in front of banks, regulators, and legal forums.',
    icon: 'FileCheck',
    heroImage: '/images/credit-report.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/c0b8caecdec9fe603253eb7d6729abb3',
    problemStatement: 'Poorly prepared documents and weak representations result in complaint rejections. Professional case preparation significantly improves your chances of success.',
    solutionPoints: [
      'Legal representation drafting',
      'Supporting document organization',
      'Affidavit preparation',
      'Case file assembly & submission',
    ],
    processSteps: [
      { step: 1, title: 'Case Review', description: 'Thoroughly review your situation and documents.' },
      { step: 2, title: 'Strategy Planning', description: 'Develop a strong narrative and documentation strategy.' },
      { step: 3, title: 'Document Preparation', description: 'Prepare representations, affidavits, and supporting docs.' },
      { step: 4, title: 'Submission & Follow-up', description: 'Submit properly and manage follow-up communication.' },
    ],
    successMetrics: [
      { metric: 'Case Success Rate', value: '87%' },
      { metric: 'Average Outcome Value', value: '₹2-4 Lakhs' },
      { metric: 'Customer Satisfaction', value: '96%' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'documentTypeNeeded', label: 'What documents do you need?', type: 'checkbox', required: true, options: [
        { label: 'Representation letter', value: 'representation' },
        { label: 'Affidavit', value: 'affidavit' },
        { label: 'NOC (No Objection Certificate)', value: 'noc' },
        { label: 'Case summary', value: 'case-summary' },
        { label: 'Ombudsman complaint format', value: 'ombudsman-format' },
      ] },
      { name: 'caseType', label: 'Type of case', type: 'select', required: true, options: [
        { label: 'Credit/Banking dispute', value: 'credit-banking' },
        { label: 'Insurance claim', value: 'insurance' },
        { label: 'Loan default', value: 'loan-default' },
        { label: 'Fraud/Unauthorized transaction', value: 'fraud' },
        { label: 'Other', value: 'other' },
      ] },
      { name: 'institutionInvolved', label: 'Financial institution involved', type: 'text', required: true },
      { name: 'urgencyLevel', label: 'How urgent is this?', type: 'radio', required: true, options: [
        { label: 'Low (2-3 weeks)', value: 'low' },
        { label: 'Medium (1-2 weeks)', value: 'medium' },
        { label: 'High (3-5 days)', value: 'high' },
      ] },
      { name: 'problemDescription', label: 'Case details & background', type: 'textarea', required: true, placeholder: 'Provide a detailed narrative of your case' },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'How long does document preparation take?', answer: 'Standard documents take 3-5 business days. Urgent requests can be done in 1-2 days.' },
      { question: 'Can you represent me in court?', answer: 'We prepare documents; legal representation would require a lawyer.' },
      { question: 'What if I don\'t have all documents?', answer: 'We help you gather necessary documents and work with what\'s available.' },
    ],
  },
  {
    id: '9',
    slug: 'cyber-fraud-support',
    title: 'Cyber Fraud Complaint Support',
    shortDescription: 'Comprehensive support for cyber fraud incidents and cybercrime complaint filing.',
    fullDescription: 'Cyber fraud victims need immediate action. We guide you through FIR filing, evidence preservation, and coordination with cybercrime authorities.',
    icon: 'Shield',
    heroImage: '/images/cyber-fraud.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/f89eeed26d5270dd336d3e9f8cd885a8',
    problemStatement: 'Cyber fraud victims are often confused about where to report and how to preserve evidence. Delay in reporting significantly reduces recovery chances.',
    solutionPoints: [
      'Immediate incident documentation',
      'FIR & cybercrime complaint filing',
      'Evidence preservation & technical support',
      'Authority coordination & follow-up',
    ],
    processSteps: [
      { step: 1, title: 'Incident Assessment', description: 'Document the cyber fraud incident with all details.' },
      { step: 2, title: 'FIR Filing', description: 'Guide you through FIR filing with local cybercrime police.' },
      { step: 3, title: 'Evidence Collection', description: 'Preserve technical evidence and digital trails.' },
      { step: 4, title: 'Investigation Tracking', description: 'Coordinate with authorities and track investigation progress.' },
    ],
    successMetrics: [
      { metric: 'FIR Filing Success', value: '98%' },
      { metric: 'Average Recovery Time', value: '30-90 days' },
      { metric: 'Fund Recovery Rate', value: '45-60%' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'fraudDate', label: 'When did the fraud occur?', type: 'date', required: true },
      { name: 'fraudType', label: 'Type of cyber fraud', type: 'checkbox', required: true, options: [
        { label: 'Unauthorized access to account', value: 'unauthorized-access' },
        { label: 'Online scam / phishing', value: 'phishing' },
        { label: 'Card fraud / payment fraud', value: 'card-fraud' },
        { label: 'Identity theft', value: 'identity-theft' },
        { label: 'Investment fraud', value: 'investment-fraud' },
        { label: 'Other', value: 'other' },
      ] },
      { name: 'amountLost', label: 'Amount lost (₹)', type: 'number', required: true },
      { name: 'platform', label: 'Platform/Institution affected', type: 'text', required: true },
      { name: 'friReported', label: 'Have you reported to police?', type: 'radio', options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ] },
      { name: 'friNumber', label: 'FIR number (if reported)', type: 'text' },
      { name: 'problemDescription', label: 'Detailed description of the fraud', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'Can I recover my stolen money?', answer: 'Yes, with proper FIR and evidence, recovery rate is 45-60% in most cases.' },
      { question: 'How quickly should I report cyber fraud?', answer: 'Report immediately within 24 hours to maximize evidence preservation and recovery chances.' },
      { question: 'Do I need to go to the police station?', answer: 'Yes, for FIR filing, but we guide you through the entire process.' },
    ],
  },
  {
    id: '10',
    slug: 'workplace-posh-complaints',
    title: 'Workplace & POSH Complaints Support',
    shortDescription: 'Expert guidance on workplace disputes, sexual harassment, and labor law violations.',
    fullDescription: 'Navigate workplace harassment and labor disputes with professional support. We ensure your complaint is filed properly and followed up effectively.',
    icon: 'Briefcase',
    heroImage: '/images/workplace.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/a2c6df51a8211f2fd54d5322066f6dea',
    problemStatement: 'Workplace harassment and labor disputes leave employees vulnerable. Many fear retaliation or don\'t know the proper complaint procedures.',
    solutionPoints: [
      'POSH complaint guidance',
      'Labor law expertise',
      'Internal complaint procedures',
      'Legal remedies & compensation',
    ],
    processSteps: [
      { step: 1, title: 'Rights Assessment', description: 'Review your rights under labor and POSH laws.' },
      { step: 2, title: 'Documentation', description: 'Gather evidence and documentation of incidents.' },
      { step: 3, title: 'Complaint Filing', description: 'File formal complaints with internal committees.' },
      { step: 4, title: 'Escalation & Support', description: 'Escalate to labor board or legal authorities if needed.' },
    ],
    successMetrics: [
      { metric: 'Complaint Resolution Rate', value: '79%' },
      { metric: 'Average Compensation', value: '₹1-3 Lakhs' },
      { metric: 'Case Duration', value: '90-180 days' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'companyName', label: 'Company/Employer name', type: 'text', required: true },
      { name: 'designation', label: 'Your designation', type: 'text', required: true },
      { name: 'issueType', label: 'Type of issue', type: 'checkbox', required: true, options: [
        { label: 'Sexual harassment (POSH)', value: 'posh' },
        { label: 'Wage/salary issues', value: 'wage-issue' },
        { label: 'Wrongful termination', value: 'termination' },
        { label: 'Labor law violation', value: 'labor-violation' },
        { label: 'Workplace discrimination', value: 'discrimination' },
        { label: 'Other', value: 'other' },
      ] },
      { name: 'incidentDate', label: 'When did the incident occur?', type: 'date', required: true },
      { name: 'complaintFiled', label: 'Have you filed an internal complaint?', type: 'radio', required: true, options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ] },
      { name: 'witnesses', label: 'Do you have witnesses?', type: 'radio', options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ] },
      { name: 'problemDescription', label: 'Detailed description of the incident', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'Can I be retaliated against for filing a POSH complaint?', answer: 'No. Anti-retaliation laws protect employees. Report any retaliation immediately.' },
      { question: 'What documentation do I need for a POSH complaint?', answer: 'Emails, messages, witness statements, and incident dates strengthen your case.' },
      { question: 'How long does a POSH investigation take?', answer: 'Typically 90-120 days from complaint filing to final report.' },
    ],
  },
  {
    id: '11',
    slug: 'recovery-sarfaesi-action',
    title: 'Recovery & SARFAESI Action Support',
    shortDescription: 'Strategic guidance on SARFAESI proceedings, debt recovery, and asset protection.',
    fullDescription: 'SARFAESI and debt recovery actions are complex. We provide expert guidance to protect your assets and negotiate favorable settlements.',
    icon: 'TrendingDown',
    heroImage: '/images/recovery.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/b9bb0931d1ac23b7747e98db85b34138',
    problemStatement: 'SARFAESI proceedings can lead to asset seizure. Without proper guidance, you may lose valuable assets without exploring negotiation options.',
    solutionPoints: [
      'SARFAESI process guidance',
      'Asset protection strategies',
      'Debt settlement negotiation',
      'Legal remedies & court options',
    ],
    processSteps: [
      { step: 1, title: 'Legal Assessment', description: 'Review your rights and SARFAESI notice validity.' },
      { step: 2, title: 'Strategy Development', description: 'Develop protection and negotiation strategy.' },
      { step: 3, title: 'Negotiation', description: 'Negotiate debt settlement or restructuring with creditors.' },
      { step: 4, title: 'Legal Action', description: 'File legal remedies and court cases if needed.' },
    ],
    successMetrics: [
      { metric: 'Settlement Negotiation Success', value: '71%' },
      { metric: 'Average Settlement Reduction', value: '15-25%' },
      { metric: 'Case Resolution Time', value: '60-120 days' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'creditorName', label: 'Name of creditor/bank', type: 'text', required: true },
      { name: 'debtAmount', label: 'Total debt amount (₹)', type: 'number', required: true },
      { name: 'assetType', label: 'Type of asset at risk', type: 'checkbox', required: true, options: [
        { label: 'Residential property', value: 'residential' },
        { label: 'Commercial property', value: 'commercial' },
        { label: 'Vehicle', value: 'vehicle' },
        { label: 'Bank account', value: 'bank-account' },
        { label: 'Business assets', value: 'business-assets' },
      ] },
      { name: 'sarfaesiNotice', label: 'Have you received SARFAESI notice?', type: 'radio', required: true, options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ] },
      { name: 'noticeDate', label: 'Date of SARFAESI notice', type: 'date' },
      { name: 'legalAction', label: 'Have you filed any legal challenge?', type: 'radio', options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ] },
      { name: 'problemDescription', label: 'Your situation and background', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'Can I stop a SARFAESI action once it starts?', answer: 'Yes, through court injunctions or by settling with the creditor.' },
      { question: 'What\'s the difference between SARFAESI and regular recovery?', answer: 'SARFAESI is a faster, extrajudicial recovery process. Legal remedies are available within 45 days of notice.' },
      { question: 'Can I negotiate a settlement after SARFAESI notice?', answer: 'Yes. Most creditors prefer settled deals over prolonged legal action.' },
    ],
  },
  {
    id: '12',
    slug: 'comprehensive-financial-problem-resolution',
    title: 'Comprehensive Financial Problem Resolution',
    shortDescription: 'All-in-one financial solutions combining credit analysis, debt management, and legal action.',
    fullDescription: 'Our flagship service offering complete financial recovery solutions. From credit repair to legal escalation, we handle all aspects of your financial problem.',
    icon: 'Zap',
    heroImage: '/images/financial-growth.jpg',
    crmFormUrl: 'https://crm.credsmadhan.com/forms/wtl/834b153fe256aa6bf40ed498149ea469',
    problemStatement: 'Financial problems are interconnected. Addressing only one issue leaves others unresolved. You need a comprehensive solution that tackles all aspects simultaneously.',
    solutionPoints: [
      'Multi-problem integrated analysis',
      'Coordinated action across all issues',
      'Single-point contact for all needs',
      'End-to-end solution coordination',
    ],
    processSteps: [
      { step: 1, title: 'Complete Financial Audit', description: 'Comprehensive analysis of all financial issues.' },
      { step: 2, title: 'Integrated Strategy Development', description: 'Create coordinated resolution strategy for all problems.' },
      { step: 3, title: 'Unified Implementation', description: 'Execute all solutions with coordinated timelines.' },
      { step: 4, title: 'Complete Resolution', description: 'Achieve full financial recovery and stability.' },
    ],
    successMetrics: [
      { metric: 'Overall Success Rate', value: '85%' },
      { metric: 'Average Resolution Time', value: '120-180 days' },
      { metric: 'Client Satisfaction', value: '94%' },
    ],
    formFields: [
      { name: 'fullName', label: 'Full Name', type: 'text', required: true },
      { name: 'phone', label: 'Phone Number', type: 'tel', required: true },
      { name: 'email', label: 'Email Address', type: 'email', required: true },
      { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
      { name: 'problemTypes', label: 'Select all applicable issues', type: 'checkbox', required: true, options: [
        { label: 'Credit report issues', value: 'credit-issues' },
        { label: 'Loan/EMI stress', value: 'loan-stress' },
        { label: 'Banking/card disputes', value: 'banking-disputes' },
        { label: 'Insurance issues', value: 'insurance-issues' },
        { label: 'Unclaimed money', value: 'unclaimed-money' },
        { label: 'Cyber fraud', value: 'cyber-fraud' },
        { label: 'Workplace issues', value: 'workplace-issues' },
        { label: 'SARFAESI/Recovery actions', value: 'recovery-action' },
        { label: 'Other', value: 'other' },
      ] },
      { name: 'totalDebt', label: 'Approximate total debt/financial exposure (₹)', type: 'number' },
      { name: 'urgencyLevel', label: 'Urgency level', type: 'radio', required: true, options: [
        { label: 'Immediate (within 7 days)', value: 'immediate' },
        { label: 'Urgent (within 1 month)', value: 'urgent' },
        { label: 'High (within 3 months)', value: 'high' },
        { label: 'Moderate (within 6 months)', value: 'moderate' },
      ] },
      { name: 'problemDescription', label: 'Detailed description of all financial problems', type: 'textarea', required: true },
      { name: 'consent', label: 'I agree to the terms and conditions', type: 'checkbox', required: true },
      { name: 'privacyConsent', label: 'I accept the privacy policy', type: 'checkbox', required: true },
    ],
    faqItems: [
      { question: 'How is comprehensive resolution different from individual services?', answer: 'We coordinate all solutions simultaneously, saving time and ensuring issues don\'t interfere with each other.' },
      { question: 'Will handling all problems at once complicate things?', answer: 'No. Our integrated approach ensures timelines are coordinated to maximize resolution efficiency.' },
      { question: 'What if new issues arise during resolution?', answer: 'Our comprehensive plan is flexible. We adapt strategy as new issues are identified and resolved.' },
    ],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find(s => s.slug === slug)
}

export function getAllServices(): Service[] {
  return services
}
